FROM node:16

# Install LibreOffice
RUN apt-get update && apt-get install -y \
    libreoffice \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Create directories for file storage
RUN mkdir -p uploads
RUN mkdir -p public/slides

# Expose the port
EXPOSE 3001

# Start the application
CMD ["node", "server.js"]
